name: VrishaliWorkflowDemo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Build File
        run: echo "Hello from GitHub Actions" > app.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: app.txt

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: demo-${{ github.run_number }}
          files: app.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
